/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FICHERO_H_RPCGEN
#define _FICHERO_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct entrada_log {
	char *usuario;
	char *operacion;
	char *fichero;
};
typedef struct entrada_log entrada_log;

#define LOGPROG 99
#define LOGVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ENVIAR_LOG 1
extern  enum clnt_stat enviar_log_1(struct entrada_log , void *, CLIENT *);
extern  bool_t enviar_log_1_svc(struct entrada_log , void *, struct svc_req *);
extern int logprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ENVIAR_LOG 1
extern  enum clnt_stat enviar_log_1();
extern  bool_t enviar_log_1_svc();
extern int logprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_entrada_log (XDR *, entrada_log*);

#else /* K&R C */
extern bool_t xdr_entrada_log ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FICHERO_H_RPCGEN */
