/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fichero.h"

bool_t
enviar_log_1_svc(struct entrada_log arg1, void *result,  struct svc_req *rqstp)
{
	/* Usamos . porque con -N se pasa por valor, no por puntero. */
    if (strlen(arg1.fichero) > 0) {
        printf("%s %s %s\n", arg1.usuario, arg1.operacion, arg1.fichero);
    } else {
        printf("%s %s\n", arg1.usuario, arg1.operacion);
    }

    return TRUE;
}

int
logprog_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
